### ISSUE TITLE
Street Fighter Alpha Anthology (USA)  ，graphic error while in software render

### ISSUE THREAD

**Issue by cjhalo** [Trixarian/NetherSX2-patch#12]
Running this game, while  switch to the software redner, the graphic shows  vertical cracks on it

![er2](https://github.com/Trixarian/NetherSX2-patch/assets/48052667/9a88d24e-dcb0-4657-8cfa-60cd9f86e27d)
![er1](https://github.com/Trixarian/NetherSX2-patch/assets/48052667/75b48512-3fa8-43df-a93b-046500e46410)

**Comment by Trixarian** [comment]
This is down to issues with Android's OpenGLES SW implementation. It doesn't work as well as OpenGL SW on the PC and has various issues. There isn't an easy fix since software rendering ignores almost all hacks and hardware fixes, so I suggest using a hardware renderer if it produces better graphics

**Comment by Trixarian** [comment]
This is bugged even in PCSX2, so I doubt there's an easy way to fix this. Closing it for now
