### ISSUE TITLE
Unable to apply patch in Linux

### ISSUE THREAD

**Issue by nesper8** [Trixarian/NetherSX2-patch#13]
I'm getting this error when trying to run the patch-apk.sh script
```
nesper8@poweredbyarch ~/Projects/NetherSX2-patch % ./patch-apk.sh   
zsh: ./patch-apk.sh: bad interpreter: /bin/bash^M: no such file or directory
```
Any way to fix this?

**Comment by Trixarian** [comment]
Install bash or make an alias for bash that points to zsh

**Comment by nesper8** [comment]
I already have bash installed and also gets the same result when running under a bash shell

**Comment by nesper8** [comment]
I tried searching this error in google
It seems that the line endings in the shell files are set to Windows Line Endings (CRLF) instead of Unix Line Endings (LF)

I had to run `sed -i -e 's/\r$//' patch-apk.sh` and `sed -i -e 's/\r$//' update-files.sh` to get them running

I'll open a PR to fix this issue

**Comment by Trixarian** [comment]
That was probably my mistake because I changed the version number. Windows code editors that shouldn't alter the line endings changing the line endings again. Github also doesn't recognize it as a change, so fixing it required moving the files out of the folder, committing, moving them back into it and committing again 🙄
