### ISSUE TITLE
Can't make shortcuts

### ISSUE THREAD

**Issue by hihihihi7657** [Trixarian/NetherSX2-patch#19]
With nethersx2 I can't make shortcuts for games on my home screen I used to be able to with aethersx2

**Comment by Trixarian** [comment]
It was removed by Talhreth to force the use of the game list within the emulator. Why? Because that's where the ads were. Re-enabling it requires redoing the IDs of the UI elements (and hand shifting 20k entries) and re-implementing the code within the core - another component we don't have open source access to (even though it's based on LGPL code).

TL;DR: We won't be readding that feature since the work involved is unreasonable. Use a game launcher app with the same feature instead
