### ISSUE TITLE
what is different between theses two files

### ISSUE THREAD

**Issue by AlirezaParsi** [Trixarian/NetherSX2-patch#20]
sorry i asked here because i found no where to ask
what is different between this two files when i finished build/patch 
![Screenshot_20231006-084433_MiXplorer](https://github.com/Trixarian/NetherSX2-patch/assets/29276037/5f03b741-d757-4082-8c7a-bc83e74adf60)

**Comment by Trixarian** [comment]
Going off the file sizes:
* Disabled and removes ads and permissions required for ads
* Removes some of the anti-tampering
* Changes the 3rdparty.html file
* Makes the icons a red cube instead of a blue one.

It also enables you to use the scripts in this repository to update and modify the contents of the apk further
