### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by m33ts4k0z** [Trixarian/NetherSX2-patch#22]
Hello and thanks for these patches.

I wonder if there is a way to apply them to the linux Appimage as well? 

thanks in advance

**Comment by Trixarian** [comment]
It's a bash script on Linux. It tries to be self-contained as possible, but it still requires some packages to be installed to work with OpenJDK being essential. If the system doesn't support the included aapt and xdelta3 binaries, then those packages need to be installed too.  Practically it won't work as an AppImage if you consider how it works, and even if I could, if would be a very large one due to the Java requirement to sign the apks

**Comment by m33ts4k0z** [comment]
Thank you but I don't think you understood what I meant 😁. AetherSX2 has an aarch64 version that is designed for SBCs as well as maybe Apple Silicon. Do we have a way to apply those patches to those releases instead of the apk?

**Comment by Trixarian** [comment]
This is meant for the Android version only. While there are ports to other ARM based systems - and you can replace the widescreen, no-interlacing, controller db and GameDB of those versions with the ones in this project - it's not within the scope of the project to cover them
