### ISSUE TITLE
Raw Danger / Zettai Zetsumei Toshi 2 (SLUS-21501) Run Worse than 3668

### ISSUE THREAD

**Issue by ISASLIMBOY28** [Trixarian/NetherSX2-patch#51]
When i played raw danger on Aethersx2 version 3668, it runs well and only some minor slow down with these settings:

Render: Vulkan
EE Cycle Rate: -1
EE Cycle Skip: Mild
Hardware Download Mode: Unsynchronized

But when i played it with Nethersx2 1.8, it runs worse only got 10 - 14 fps with safe or unsafe setting or settings that i used in aethersx2.

Screenshot from aethersx2 3668:
![Screenshot_20240307-063505](https://github.com/Trixarian/NetherSX2-patch/assets/70120519/11b6018b-a4b6-4efb-8d3b-363a392d8947)

Screenshot from nethersx2 1.8:
![Screenshot_20240307-063130](https://github.com/Trixarian/NetherSX2-patch/assets/70120519/8e69d85b-63bf-406e-8292-60cbac2913f2)

Update: Also tested on OpenGL, it's the same.

**Comment by Trixarian** [comment]
With some games performance is worse with 4248 (which NetherSX2 is based on) than it is with 3668. This is due to core changes made in the months between the two which corrected several bugs and fixed the lighting for many games, but also increased the requirements for the emulator when dealing with those fixes. In cases like this, I suggest using 3668 (or NetherSX2 Classic) for the affected games since it will be a much more pleasant experience
