### ISSUE TITLE
"A copy of the NetherSX2 APK" Shouldn't this be aethersx2 ?

### ISSUE THREAD

**Issue by xpufx** [Trixarian/NetherSX2-patch#52]
From the README. Linux prerequisites section.

**Comment by Trixarian** [comment]
The ability to turn the AetherSX2 apk into NetherSX2 is a recent addition (added in 1.7). Originally NetherSX2-patch was just a batch script that updated existing copies of NetherSX2 by adding newer files. Since I wanted to add more advanced changes, it meant modding NetherSX2 in more ways than simply updating of the files could allow. The patching method I use is also very particular about file hashes matching, so I needed a constant, which is why we're using AetherSX2 4248 as the basis. NetherSX2 is too much of a variable, since generating it by the termux method will always give you a different file hash

**Comment by TheBoxGame** [comment]
@Trixarian I have a request for you, can you help me fix the game Top Gun Combat Zone so that the fps doesn't drop in random places in the game, even in mission 1 the fps drops, I tried different settings and it's the same
