### ISSUE TITLE
Actualization NetherSX2

### ISSUE THREAD

**Issue by TheBoxGame** [Trixarian/NetherSX2-patch#53]
@Trixarian I have a request for you aethersx2 will have updates so that games don't drop in random places, I mean Top Gun Combat Zone Juiced 2 Gradius V and even MTX Mototrax in the first boss fight, fps drops terribly even with random settings and other games

**Comment by Trixarian** [comment]
There may or may not be improvements added in the future for games as I come across them

This is mostly caused by the game reaching a point where it's asking for something that's hard or slow to render - like transfers - which is why I generally suggest putting Hardware Download Mode on Disable Transfers to help deal with the biggest performance sink in PS2 emulation. It's not a perfect solution and it will break games that require it to be set to Accurate (like Fatal Frame), but it's the second biggest performance gain you can use

**Comment by TheBoxGame** [comment]
Uploading Screenrecorder-2024-05-04-15-59-42-518.mp4…
