### ISSUE TITLE
Add Storage Access

### ISSUE THREAD

**Issue by noggl** [Trixarian/NetherSX2-patch#61]
Similar to #59 I'd like to ask whether it is possible to implement storage access for the scoped storage that Aether/Nether uses. Similar to Yuzu/Citra and other apps, this would allow storage access to the data folders by the android file manager and by other applications (Like FolderSync) by requesting the appropriate permissions.

See picture below from [Dr4goonD3mon](https://github.com/Dr4goonD3mon)'s original issue
![image](https://github.com/Trixarian/NetherSX2-patch/assets/67533630/ea0fa818-dd6f-416d-9456-ad3ef86a0c81)

**Comment by Trixarian** [comment]
Not really possible with the current reverse engineered version of AetherSX2 since those paths are built into the emulation core and not easy to change as a result. Future versions of NetherSX2 that is built from scratch using our own front end and core based on PCSX2 will have this feature since scoped storage in Android 11 and up has become problematic
